services:
  api:
    container_name: api
    build: ./api
    environment:
      - MYSQL_PASSWORD=123
      - MYSQL_USER=admin
      - MYSQL_HOST=mysql
      - PORT=8080
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - blog
  client: 
    build: ./Blog
    ports:
      - 3000:3000
    networks:
      - blog
    volumes:
      - ./Blog:/Client
  database:
    container_name: mysql
    hostname: mysql
    image: mysql:5.7
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--innodb_monitor_enable=all", "--max-connections=1001"]
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=blog
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
    ports:
      - 3305:3306
      - 33050:33060
    networks:
      - blog
    expose:
      - 3305
    volumes:
      - ./api/src/db/init.sql:/docker-entrypoint-initdb.d/schema.sql:ro

networks:
  blog:
    driver: bridge
